/**
 * codebakers_generate_migration
 *
 * Database Migration Generator
 *
 * Generates Supabase/PostgreSQL migration files from entity definitions.
 * Includes: tables, columns, foreign keys, indexes, RLS policies
 */

import * as fs from 'fs/promises';
import * as path from 'path';

interface MigrationArgs {
  entity: string;
  fields: { name: string; type: string; required?: boolean; references?: string }[];
  add_rls?: boolean;
}

export async function generateMigration(args: MigrationArgs): Promise<string> {
  const cwd = process.cwd();
  const { entity, fields, add_rls = true } = args;

  console.error(`🍞 CodeBakers: Generating migration for ${entity}`);

  try {
    const tableName = entity.toLowerCase() + 's';
    const timestamp = new Date().toISOString().replace(/[-:]/g, '').split('.')[0];
    const filename = `${timestamp}_create_${tableName}.sql`;

    let sql = `-- Create ${entity} table\n-- Generated by CodeBakers\n\n`;

    // Extension
    sql += `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n\n`;

    // Create table
    sql += `CREATE TABLE ${tableName} (\n`;
    sql += `  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n`;
    sql += `  user_id UUID REFERENCES auth.users NOT NULL,\n`;

    for (const field of fields) {
      const type = mapType(field.type);
      const nullable = field.required ? ' NOT NULL' : '';
      sql += `  ${field.name} ${type}${nullable},\n`;
    }

    sql += `  created_at TIMESTAMPTZ DEFAULT NOW(),\n`;
    sql += `  updated_at TIMESTAMPTZ DEFAULT NOW()\n`;
    sql += `);\n\n`;

    // Indexes
    sql += `CREATE INDEX idx_${tableName}_user_id ON ${tableName}(user_id);\n`;
    sql += `CREATE INDEX idx_${tableName}_created_at ON ${tableName}(created_at DESC);\n\n`;

    // RLS
    if (add_rls) {
      sql += `ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;\n\n`;
      sql += `CREATE POLICY "Users see own ${tableName}"\nON ${tableName} FOR SELECT\nUSING (auth.uid() = user_id);\n\n`;
      sql += `CREATE POLICY "Users insert own ${tableName}"\nON ${tableName} FOR INSERT\nWITH CHECK (auth.uid() = user_id);\n\n`;
      sql += `CREATE POLICY "Users update own ${tableName}"\nON ${tableName} FOR UPDATE\nUSING (auth.uid() = user_id);\n\n`;
      sql += `CREATE POLICY "Users delete own ${tableName}"\nON ${tableName} FOR DELETE\nUSING (auth.uid() = user_id);\n`;
    }

    // Write file
    const migrationDir = path.join(cwd, 'supabase', 'migrations');
    await fs.mkdir(migrationDir, { recursive: true });
    const migrationPath = path.join(migrationDir, filename);
    await fs.writeFile(migrationPath, sql, 'utf-8');

    return `🍞 CodeBakers: Migration Generated

**File:** supabase/migrations/${filename}
**Table:** ${tableName}
**Fields:** ${fields.length}
**RLS:** ${add_rls ? 'Enabled' : 'Disabled'}

Migration includes:
✅ Table creation with UUID primary key
✅ user_id foreign key (security)
✅ Timestamps (created_at, updated_at)
✅ Indexes (user_id, created_at)
${add_rls ? '✅ RLS policies (user isolation)' : ''}

**Apply migration:**
\`\`\`bash
supabase db push
\`\`\`

Or manually:
\`\`\`bash
psql -f supabase/migrations/${filename}
\`\`\``;
  } catch (error) {
    return `🍞 CodeBakers: Migration Failed\n\nError: ${error instanceof Error ? error.message : String(error)}`;
  }
}

function mapType(type: string): string {
  const lower = type.toLowerCase();
  if (lower === 'string') return 'TEXT';
  if (lower === 'number') return 'INTEGER';
  if (lower === 'boolean') return 'BOOLEAN';
  if (lower === 'date') return 'TIMESTAMPTZ';
  if (lower === 'uuid') return 'UUID';
  if (lower === 'json') return 'JSONB';
  return 'TEXT';
}
